version: '2.1'

services:
  spotify:
    privileged: true 
    build:
      context: ./
      dockerfile: spotify-vpn.dockerfile
    volumes: 
      - /tmp/.X11-unix:/tmp/.X11-unix
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    devices: 
      - "/dev/net/tun:/dev/net/tun"
    sysctls:
      - net.ipv4.conf.all.rp_filter=2